services:
  front-dev:
    image: frontend-dev
    build: 
      context: ./frontend
      dockerfile: ./dev.Dockerfile
    volumes:
      - ./frontend/:/usr/src/my-app/frontend
    container_name: frontend-dev
  back-dev:
    image: backend-dev
    build: 
      context: ./backend
      dockerfile: ./dev.Dockerfile
    volumes:
      - ./backend/:/usr/src/todo-app/todo-backend
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: my-app-reverse-proxy
    depends_on:
      - front-dev
      - back-dev